### ISSUE TITLE
Change authorization header

### ISSUE THREAD

**Issue by BenjaminArfa** [supabase-community/postgrest-go#22]
After looking a bit at the supabase documentation, I saw that the authentication is not Basic but Bearer (which means in return that one should have to change this in the client.go file of postgrest.)
I propose two solution:
- whether to amend it on the static string of the TokenAuth (I just did it myself line 59 of client.go). then is will go to 
```golang
func (c *Client) TokenAuth(token string) *Client {
	c.clientTransport.header.Set("Authorization", "Bearer "+token)
        ...
}
\\ instead of 
func (c *Client) TokenAuth(token string) *Client {
	c.clientTransport.header.Set("Authorization", "Basic "+token)
        ...
}
```

- or to amend it dynamically (I do not really now how PostgreSQL works, so if there are different type of authorization I could envisage the following)
```golang
func (c *Client) TokenAuth(token string, auth_type string) *Client {
	c.clientTransport.header.Set("Authorization", auth_type+" "+token)
        ...
} 
\\ instead of 
func (c *Client) TokenAuth(token string) *Client {
	c.clientTransport.header.Set("Authorization", "Basic "+token)
        ...
}```

**Comment by yusufpapurcu** [comment]
Yep you are right I will change it to "Bearer" after testing 👍

**Comment by yusufpapurcu** [comment]
Solved, thanks for warning @BenjaminArfa 💯
