### ISSUE TITLE
❓ Can't get it to work.

### ISSUE THREAD

**Issue by AlbinoGeek** [supabase-community/postgrest-go#27]
## Synopsis

I can't get this package to function against `supabase.co`

## Details

Whether I use the Anon key or the Service key, I can't select anything.

- With `head` set to `false`, I get `[]`
- With `head` set to `true`, I get `""`

## Reproduction

```go
func TestSelect(t *testing.T) {
	db := postgrest.NewClient(
		"https://<project-ref>.supabase.co/rest/v1/",
		"public",
		map[string]string{},
	)
	db.TokenAuth("...")

	res, count, err := db.
		From("profiles").
		Select("*", "", false). // also tried specifying columns
		ExecuteString()

	spew.Dump(res, count, err)

	if err != nil {
		t.Fatalf("error returned: %v", err)
	}

	if res == "[]" || res == "" {
		t.Fatalf("no result")
	}
}
```

```
=== RUN   TestSelect
(string) (len=2) "[]"
(int64) 0
(interface {}) <nil>
    select_test.go:30: no result
--- FAIL: TestSelect (0.29s)
```

**Comment by yusufpapurcu** [comment]
Hey If you have time we can look into it on discord. You can pick a time after 5pm GMT 🙂

**Comment by yusufpapurcu** [comment]
Ok this is a bigger issue than I expected and it seems like it completely take down every request which done by library.
