### ISSUE TITLE
Supabase URL needs `/rest/v1` appended

### ISSUE THREAD

**Issue by mrcampbell** [supabase-community/postgrest-go#28]
In the README, the docs say to put in `localhost:3000`, but if calling supabase itself, if you put in the API URL as it is in Supabase, you get a `() no Route matched with those values` error.

I had to update my URL to `https://<database id>.supabase.co/rest/v1` and it worked.

Could we update the docs?  Or is there a fix under the hood we'd want to make?  I'm up to make either, but wanted to run it by you all first!

**Comment by yusufpapurcu** [comment]
We should do this in docs. Thanks for raising that 🙌

**Comment by drev74** [comment]
@mrcampbell Thanks for the fix. I encountered this issue in a dependent project. Pls fix the docs

**Comment by mrcampbell** [comment]
I can pick this up! Sorry I forgot about it!

**Comment by muratmirgun** [comment]
Happy Hacking @mrcampbell

**Comment by mantism** [comment]
@muratmirgun @mrcampbell ran into this issue yesterday, since this has been open for a while, and if there's no PR in progress can I assign this to myself and propose a README change to include this and maybe some QueryBuilder examples?

**Comment by tranhoangvuit** [comment]
We have updated the README to include the `rest/v1`.
