### ISSUE TITLE
Implement a Single method

### ISSUE THREAD

**Issue by inian** [supabase-community/postgrest-go#8]
Similar to https://supabase.io/docs/reference/javascript/single

**Comment by yusufpapurcu** [comment]
Single method is exist but in unusable status. We need think about how can we add them to flow.

**Comment by yusufpapurcu** [comment]
Actually all transform builders in unusable status.

**Comment by bariqhibat** [comment]
Hey @inian, I saw that this method is implemented already in the transform builder https://github.com/supabase-community/postgrest-go/blob/main/transformbuilder.go#L83

**Comment by yusufpapurcu** [comment]
Yes it is implemented in transform builders. But they are unusable because of current builder architecture. We must design a better architecture for this project.

**Comment by bariqhibat** [comment]
> Yes it is implemented in transform builders. But they are unusable because of current builder architecture. We must design a better architecture for this project.

Can the single just use the limit method and take only one? It'll still return an array, but still makes sense

**Comment by yusufpapurcu** [comment]
Yes we can do this but this method is not correct I think. True one is implementing every transform builders to the architecture. Actually we can talk this architect changes in another issue 😄

**Comment by bariqhibat** [comment]
> Yes we can do this but this method is not correct I think. True one is implementing every transform builders to the architecture. Actually we can talk this architect changes in another issue 😄

Yeah that makes sense.. Sure, thanks Yusuf!
